### ISSUE TITLE
配置到 one-api 后测试提示 错误：type api_error, code prompt_missing, message prompt is required

### ISSUE THREAD

**Issue by sun-i** [MagicalMadoka/cf-sd-to-dalle3#1]
### one-api 配置
![image](https://github.com/MagicalMadoka/cf-sd-to-dalle3/assets/111034439/655dc684-99c8-4ddd-a35a-a35b4f2ee26b)
### 报错
![image](https://github.com/MagicalMadoka/cf-sd-to-dalle3/assets/111034439/f96298a0-5ca0-4d76-8638-7d25b1fb9b93)

**Comment by MagicalMadoka** [comment]
这个和oneapi的测试机制有关。详细的你可以看看他的说明。但是不影响使用。
